name: filo_menu
description: "Filo Menu: The Modern Restaurant App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.1.0  # ğŸ‘ˆ Ø£Ø¶Ù Ù‡Ø°Ù‡
  qr_flutter: ^4.1.0      # ğŸ‘ˆ Ø£Ø¶Ù Ù‡Ø°Ù‡ Ø§Ù„Ù…ÙƒØªØ¨Ø© Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø©
  # Ø­Ø²Ù…Ø© Ù„Ù„ØªÙˆØ§ØµÙ„ Ù…Ø¹ Ø§Ù„Ø³ÙŠØ±ÙØ± (Ù„Ø±Ø¨Ø· API Ù„Ø§Ø­Ù‚Ø§Ù‹)
  http: ^1.2.1
  video_player: ^2.8.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  google_sign_in: ^6.1.0
  intl_phone_field: ^3.2.0
  connectivity_plus: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Ø­Ø²Ù… ØªØ®ØµÙŠØµ Ø§Ù„Ù‡ÙˆÙŠØ© Ø§Ù„Ø¨ØµØ±ÙŠØ© Ù„Ù€ Filo Menu
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.3.1"

# Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø­Ø²Ù…Ø© Ø§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø§Øª (Flutter Launcher Icons)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/filo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/filo.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
    
# Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø­Ø²Ù…Ø© Ø´Ø§Ø´Ø© Ø§Ù„Ø¨Ø¯Ø§ÙŠØ© (Flutter Native Splash)
flutter_native_splash:
  # Ø§Ù„ØµÙˆØ±Ø© Ø§Ù„ØªÙŠ ØªØ±ÙŠØ¯Ù‡Ø§ ÙƒØ®Ù„ÙÙŠØ©
  background_image: "assets/icons/splash_bg.png"
  
  # Ù„ÙˆÙ† Ø§Ù„Ø®Ù„ÙÙŠØ© (Ø§Ø­ØªÙŠØ§Ø·ÙŠ)
  color: "#1A1A1A"

  # 1. Ø¥Ø®ÙØ§Ø¡ Ø´Ø±ÙŠØ· Ø§Ù„Ø­Ø§Ù„Ø© (Ø§Ù„Ø³Ø§Ø¹Ø© ÙˆØ§Ù„Ø¨Ø·Ø§Ø±ÙŠØ©) Ù„ØªØµØ¨Ø­ Ø§Ù„Ø´Ø§Ø´Ø© ÙƒØ§Ù…Ù„Ø©
  fullscreen: true

  # 2. Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø£Ù†Ø¯Ø±ÙˆÙŠØ¯ (Ù„Ø¬Ø¹Ù„ Ø§Ù„ØµÙˆØ±Ø© ØªÙ…Ø· ÙˆØªÙ…Ù„Ø£ Ø§Ù„Ø´Ø§Ø´Ø©)
  android_gravity: fill
  
  # 3. Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø¢ÙŠÙÙˆÙ† (ØªØºØ·ÙŠØ© ÙƒØ§Ù…Ù„Ø© Ù…Ø¹ Ù‚Øµ Ø§Ù„Ø²ÙˆØ§Ø¦Ø¯)
  ios_content_mode: cover
  
  # 4. (Ù…Ù‡Ù… Ø¬Ø¯Ø§Ù‹) Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø£Ù†Ø¯Ø±ÙˆÙŠØ¯ 12 ÙÙ…Ø§ ÙÙˆÙ‚
  # Ø£Ù†Ø¯Ø±ÙˆÙŠØ¯ 12 ÙŠÙ…Ù†Ø¹ ØµÙˆØ± Ø§Ù„Ø®Ù„ÙÙŠØ© Ø§Ù„ÙƒØ§Ù…Ù„Ø© ÙÙŠ Ø§Ù„Ø³Ø¨Ù„Ø§Ø´ Ø³ÙƒØ±ÙŠÙ† Ø§ÙØªØ±Ø§Ø¶ÙŠØ§Ù‹
  # Ù‡Ø°Ø§ ÙŠØ­Ø§ÙˆÙ„ Ø¬Ø¹Ù„Ù‡Ø§ Ø£Ù‚Ø±Ø¨ Ù…Ø§ ÙŠÙ…ÙƒÙ†ØŒ Ù„ÙƒÙ†Ù‡ Ø³ÙŠØ¸Ù‡Ø± Ø§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø© ÙÙŠ Ø§Ù„ÙˆØ³Ø·
  android_12:
    color: "#1A1A1A"
    # ÙŠÙØ¶Ù„ Ø§Ø³ØªØ®Ø¯Ø§Ù… Ø£ÙŠÙ‚ÙˆÙ†Ø© ØµØºÙŠØ±Ø© Ù‡Ù†Ø§ Ù„Ù„Ø£Ù†Ø¯Ø±ÙˆÙŠØ¯ 12ØŒ Ø£Ùˆ ØªØ±ÙƒÙ‡Ø§ ØªØ£Ø®Ø° Ø§Ù„Ø§ÙØªØ±Ø§Ø¶ÙŠ
    # image: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  # Ø§Ù†ØªØ¨Ù‡: ÙƒÙ„Ù…ØªÙŠ assets ØªØ­Øª Ø¨Ø¹Ø¶Ù‡Ù…Ø§ ØªÙ…Ø§Ù…Ø§Ù‹
  assets:
    - assets\icons\filo.png
    - assets\icons\splash_bg.png
    - assets\videos\intro.mp4